# Use a lightweight Node.js image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the app's source code
COPY . .

# Build the app in production mode
RUN npm run build

# Expose the port
EXPOSE 4200

# Start the app in production mode
CMD ["npm", "run", "start:prod"]
